--- #YAML:1.0
abstract: 'Create a ticket in relation to one or more i-doit objects'
author:
  - 'Benjamin Heisig <bheisig@synetics.de>'
  - 'Leonard Fischer <lfischer@synetics.de>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
requires:
  perl: 5.10.0
  rt: 4.0.0
distribution_type: module
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-ReferenceIDoitObjects
no_index:
  file:
    - TODO
  directory:
    - etc
    - html
    - inc
    - po
    - t
resources:
  license: http://dev.perl.org/licenses/
  repository: git://git.benjaminheisig.net/rt-extension-referenceidoitobjects.git
version: 0.2
